jobs:
  generic_handler:
    name: "\u8986\u76D6\u7387\u7EDF\u8BA1"
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        cache: maven
        cache-dependency-path: '**/pom.xml'
        check-latest: true
        distribution: zulu
        java-version: 21
    - continue-on-error: true
      name: Build with Maven - other
      run: mvn -B package -DskipAntRunForJenkins --file pom.xml -pl '!frontend'
    - continue-on-error: true
      name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
name: "MeterSphere \u8986\u76D6\u7387\u7EDF\u8BA1"
on:
  repository_dispatch:
    types: trigger-ga___codecov.yml
permissions:
  pull-requests: write
