jobs:
  generic_handler:
    name: "\u81EA\u52A8\u521B\u5EFA PR"
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
      name: Create pull request
      uses: jumpserver/action-generic-handler@master
name: "\u9488\u5BF9\u7279\u5B9A\u5206\u652F\u540D\u81EA\u52A8\u521B\u5EFA PR"
on:
  repository_dispatch:
    types: trigger-ga___create-pr-from-push.yml
