jobs:
  generic_handler:
    name: "\u524D\u7AEF\u4EE3\u7801\u6821\u9A8C"
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        cache: maven
        cache-dependency-path: '**/pom.xml'
        check-latest: true
        distribution: zulu
        java-version: 21
    - continue-on-error: true
      name: Build with Maven - only frontend
      run: mvn -T 1C -B package --file pom.xml -pl frontend
name: "MeterSphere \u524D\u7AEF\u4EE3\u7801\u6821\u9A8C"
on:
  repository_dispatch:
    types: trigger-ga___frontend-build.yml
permissions:
  pull-requests: write
