jobs:
  issue-open-add-labels:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      if: ${{ !github.event.issue.pull_request }}
      name: Add labels
      uses: actions-cool/issues-helper@v2
      with:
        actions: add-labels
        labels: "\u72B6\u6001:\u5F85\u5904\u7406"
name: Issue Open Check
on:
  repository_dispatch:
    types: trigger-ga___issue-open.yml
