jobs:
  check-recent-issues-not-handle:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      name: Check recent issues and send msg
      uses: jumpserver/action-issues-alert@master
      with:
        hook: ${{ secrets.WECHAT_GROUP_WEB_HOOK }}
        type: recent
name: Check recent handle issues
on:
  repository_dispatch:
    types: trigger-ga___issue-recent-alert.yml
