jobs:
  check-untimely-handle-issues:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      name: Check untimely issues and send msg
      uses: jumpserver/action-issues-alert@master
      with:
        hook: ${{ secrets.WECHAT_GROUP_WEB_HOOK }}
        type: untimely
name: Check untimely handle issues
on:
  repository_dispatch:
    types: trigger-ga___issue-untimely-alert.yml
