jobs:
  run:
    name: Sync-GitHub-to-Gitee
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Mirror the Github repos to Gitee.
      uses: Yikun/hub-mirror-action@master
      with:
        account_type: org
        dst: gitee/fit2cloud-feizhiyun
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
        dst_token: ${{ secrets.GITEE_TOKEN }}
        force_update: true
        src: github/metersphere
        static_list: MeterSphere
name: Mirror GitHub Auto Queried Repos to Gitee
on:
  repository_dispatch:
    types: trigger-ga___sync-to-gitee.yml
